language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t norbidocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true norbidocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-east-2-315592433248"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY